version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GCP_PROJECT_ID=ecommerce-analytics-491215
      - SECRET_KEY=sua-chave-secreta-muito-segura
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000

  dashboard:
    build: .
    ports:
      - "8050:8050"
    environment:
      - GCP_PROJECT_ID=ecommerce-analytics-491215
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    command: python -m src.dashboard.app